title: "[Feature Request] "
labels: ["Feature Request Form"]
body:
  - type: markdown
    attributes:
      value: "#Feature Details"
  - type: input
    attributes:
      label: Feature Name
      description: [Provide a concise name for the feature]
    validations:
      required: true
  - type: input
    attributes:
      label: Description
      description: [A brief and clear label of the feature. Explain what problem it solves or what improvement it brings.]
    validations:
      required: true
  - type: input
    attributes:
      label: Use Case
      description: [Describe the specific scenarios or situations where this feature would be useful.]
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Priority
      options:
        - Low
        - Medium
        - High
        - Critical
    validations:
      required: true
  - type: input
    attributes:
      label: Benefit
      description: [Explain the benefits of implementing this feature, such as increased user engagement, improved user experience, or revenue potential.]
    validations:
      required: true
  - type: input
    attributes:
      label: User
      description: [Specify the target user or customer segment for this feature, if applicable.]
    validations:
      required: true
  - type: markdown
    attributes:
      value: "#Technical Details"
  - type: input
    attributes:
      label: Integration
      description: [Explain how this feature will integrate with existing features, if applicable.]
    validations:
      required: true
  - type: input
    attributes:
      label: Dependencies
      description: [List any third-party tools, services, or APIs that this feature may depend on.]
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Technical
      options:
        - Low
        - Medium
        - High
        - Unsure
    validations:
      required: true
  - type: input
    attributes:
      label: Estimated
      description: [Provide an estimate of the time required for development, if known.]
    validations:
      required: true
  - type: markdown
    attributes:
      value: "#Design and UI/UX"
  - type: input
    attributes:
      label: Design
      description: [Describe any specific design requirements or considerations for this feature, such as branding, color schemes, or user interface elements.]
    validations:
      required: true
  - type: input
    attributes:
      label: Wireframes/Visuals
      description: [Attach any wireframes, mockups, or visuals that help illustrate the desired user interface for this feature.]
    validations:
      required: true
  - type: markdown
    attributes:
      value: "#Testing and QA"
  - type: input
    attributes:
      label: Testing
      description: [Outline any specific testing criteria or scenarios that need to be addressed during development and quality assurance.]
    validations:
      required: true
  - type: markdown
    attributes:
      value: "#Development Time Estimate"
  - type: dropdown
    attributes:
      label: Testing
      options:
        - Days
        - Weeks
        - Months
        - Unsure
    validations:
      required: true
  - type: markdown
    attributes:
      value: "#Marketing and Communication"
  - type: input
    attribute:
      label: Communications Plan
      description: [Suggest how this feature should be communicated to existing and potential customers. Include ideas for blog posts, emails, or social media announcements.]
    validations:
      required: true
  - type: input
    attribute:
      label: Sales Impact
      description: [Provide insights into how this feature might impact the sales team and their efforts.]
    validations:
      required: true
  - type: markdown
    attributes:
      value: "#Additional Notes"
  - type: input
    attribute:
      label: Sales Impact
      description: [Include any additional information, ideas, or considerations that may be relevant to this feature request.]
    validations:
      required: true
