title: "[Feature Request] "
labels: ["Feature Request Form"]
body:
  - type: markdown
    attributes:
      value: |
        ## Markdown header
  - type: input
    id: has-id
    attributes:
      label: Suggestions
      description: A description about suggestions to help you
    validations:
      required: true
