title: "[Feature Request] "
labels: ["Feature Request Form"]
body:
  - type: markdown
    attributes:
      value: "#Feature Details"
  - type: input
    attributes:
      label: Feature Name
      description: [Provide a concise name for the feature]
    validations:
      required: true
