title: "[Feature Request] "
labels: ["Feature Request Form"]
body:
  - type: markdown
    attributes:
      value: |
        ## Feature Details
  - type: input
    id: name
    attributes:
      label: Feature Name
      description: [A brief and clear description of the feature. Explain what problem it solves or what improvement it brings.]
    validations:
      required: true
